plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'eclipse'
	id 'net.neoforged.moddev' version '1.0.1'
    id "me.modmuss50.mod-publish-plugin" version "0.4.5"
}

repositories {
    maven { url = 'https://maven.creeperhost.net/' }
    maven { url "https://www.cursemaven.com" }
}

version = '2.0.1'
group = 'com.vadis365.uppers'
base {
    archivesName = "uppers"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
sourceSets.main.resources { srcDir 'src/generated/resources' }

runs {
    configureEach {
        jvmArgument '-Xmx8G'

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', "uppers"
        programArguments.addAll('--width', '1280', '--height', '720')
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', "uppers"
        programArgument '--nogui'
    }

    gameTestServer {
        systemProperty 'forge.enabledGameTestNamespaces', "uppers"
    }

    data {
        programArguments.addAll '--mod', "uppers", '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
}

jar {
    manifest {
        attributes([
            "Specification-Title": "uppers",
            "Specification-Vendor": "vadis365",
            "Specification-Version": "1", // We are version 1 of ourselves
            "Implementation-Title": project.name,
            "Implementation-Version": "2.0.1",
            "Implementation-Vendor" :"",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}