modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/vadis365/Uppers/issues"

[[mods]]
modId="uppers"
version="${file.jarVersion}"
displayName="Uppers"
displayURL="https://github.com/vadis365/Uppers"
credits="Thanks to people and stuff."
authors="vadis365" #optional
description='''
A mod that adds upside-down hoppers.
'''
[[dependencies.uppers]]
modId="neoforge"
required=true
versionRange="[20.4,)"
ordering="NONE"
side="BOTH"