modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/vadis365/Uppers/issues"
displayURL="https://github.com/vadis365/Uppers"
[[mods]]
modId="uppers"
version="1.0.1"
displayName="Uppers"
credits="Thanks to people and stuff."
authors="vadis365" #optional
description='''
A mod that adds upside-down hoppers.
'''
[[dependencies.uppers]]
modId="forge"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"